/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.myfaces.custom.dojolayouts;

import org.apache.myfaces.custom.dojo.DojoWidget;

/**
 * PanelGroup which supports a partialTriggers Attribute similar to the one in Trinidad
 * 
 * @JSFComponent
 *   name = "s:layoutingSplitPane"
 *   class = "org.apache.myfaces.custom.dojolayouts.DojoSplitPane"
 *   superClass = "org.apache.myfaces.custom.dojolayouts.AbstractDojoSplitPane"
 *   parent = "javax.faces.component.UIOutput"
 *   tagClass = "org.apache.myfaces.custom.dojolayouts.DojoSplitPaneTag"
 *   
 *
 */
public abstract class AbstractDojoSplitPane extends DojoContentPane implements DojoWidget {

    public static final String COMPONENT_TYPE        = "org.apache.myfaces.DojoSplitPane";

    public static final String COMPONENT_FAMILY      = "javax.faces.Output";

    public static final String DEFAULT_RENDERER_TYPE = "org.apache.myfaces.DojoSplitPaneRenderer";

     /**
      * Optional enforced dojo widgetId
      * 
      * @JSFProperty
      */
    public abstract String getWidgetId();

    /**
     *  optional widget var name, if this is not used only an autogenerated value is set
     * 
     * @JSFProperty
     */
    public abstract java.lang.String getWidgetVar();

    /**
     * horizontal or vertical
     * 
     * @JSFProperty
     */
    public abstract String getOrientation();

    /**
     * width of the sizer bar
     * 
     * @JSFProperty
     */
    public abstract Integer getSizerWidth();

    /**
     * Size share value describing the place the content pane wants from its parent
     * 
     * @JSFProperty
     */
    public abstract Integer getActiveSizing();

    /**
     * If true, cookie persisting of the split pane is enabled
     * 
     * @JSFProperty
     */
    public abstract Boolean getPersist();

    /**
     * Last point of the split pane
     * 
     * @JSFProperty
     */
    public abstract Integer getLastPoint();

    /**
     * Starting Point of the split pane as defined by dojo
     * 
     * @JSFProperty
     */
    public abstract Integer getStartPoint();
    
    /**
     * The CSS class for this element. Corresponds to the HTML 'class' attribute.
     * 
     * @JSFProperty
     */
    public String getStyle(){
        return super.getStyle();
    }

    /**
     *  The CSS class for this element. Corresponds to the HTML 'class' attribute.
     *  
     * @JSFProperty
     */
    public String getStyleClass(){
        return super.getStyleClass();
    }
    
    /**
     * Size share value describing the place the content pane wants from its parent
     * 
     * @JSFProperty
     */
    public Integer getSizeShare(){
        return super.getSizeShare();
    }
    
}
