/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.myfaces.custom.dialog;

import javax.faces.component.UIPanel;

import org.apache.myfaces.custom.dojo.DojoWidget;

/**
 * Modal Dojo Dialog (is not working with overridden 'onload')
 * 
 * @JSFComponent
 *   name = "s:modalDialog"
 *   class = "org.apache.myfaces.custom.dialog.ModalDialog"
 *   superClass = "org.apache.myfaces.custom.dialog.AbstractModalDialog"
 *   tagClass = "org.apache.myfaces.custom.dialog.ModalDialogTag"
 *   
 */
public abstract class AbstractModalDialog extends UIPanel implements DojoWidget {

    public static final String COMPONENT_TYPE = "org.apache.myfaces.ModalDialog";

    public static final String DEFAULT_RENDERER_TYPE = "org.apache.myfaces.ModalDialog";
    
	/**
	 * A space separated list with attribute='value' pairs, which control the behaviour of the dojo dialog.
	 * 
	 * @JSFProperty
	 */
	public abstract String getDialogAttr();

    /**
     * The id to control the dialog (dojo widget) with javascript.
     * 
     * @JSFProperty
     */
	public abstract String getDialogId();

    /**
     * The name of the variable to control the dialog (dojo widget) with javascript.
     * 
     * @JSFProperty
     */
    public abstract String getDialogVar();
    
    public abstract void setDialogVar(String dialogVar);

    /**
     * A comma separated list with ids of input-elements, which can tell (by javascript-code) the dialog to hide.
     * 
     * @JSFProperty
     */
	public abstract String getHiderIds();

    /**
     * The URL of the view to show within the content area of the dialog
     * 
     * @JSFProperty
     */
	public abstract String getViewId();

	//@Override
	public boolean getRendersChildren() {
    	return true;
	}

    /**
     * HTML: CSS styling instructions.
     * 
     * @JSFProperty
     */
	public abstract String getStyle();

    /**
     * The CSS class for this element. Corresponds to the HTML 'class' attribute.
     * 
     * @JSFProperty
     */
	public abstract String getStyleClass();

    /**
     * Optional enforced dojo widgetId
     *  
     * @JSFProperty
     */
	public abstract String getWidgetId();

    /**
     * The title text to show in the title area
     * 
     * @JSFProperty
     */
	public abstract String getDialogTitle();

    /**
     * true|false - Set to true if a close button should be rendere within the 
     * title area (requires a dialogTitle)
     * 
     * @JSFProperty
     */
	public abstract Boolean getCloseButton();

	/**
	 * optional widget var name, if this is not used only an autogenerated value is set
	 * 
	 * @JSFProperty
	 */
	public String getWidgetVar() {
        return getDialogVar();
    }

	public void setWidgetVar(String widgetVar) {
       setDialogVar(widgetVar);
    }
}
