/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.myfaces.custom.dojolayouts;

import javax.faces.component.UIOutput;

import org.apache.myfaces.custom.dojo.DojoWidget;

/**
 * Base content pane for the dojo layouts
 * 
 * jsfed dojo content pane
 * 
 * @see http://www.dojotoolkit.org for further references to this control and
 *      its parameters
 * 
 * @JSFComponent
 *   name = "s:layoutingContentPane"
 *   class = "org.apache.myfaces.custom.dojolayouts.DojoContentPane"
 *   superClass = "org.apache.myfaces.custom.dojolayouts.AbstractDojoContentPane"
 *   tagClass = "org.apache.myfaces.custom.dojolayouts.DojoContentPaneTag"
 *   
 * @author werpu
 * 
 */
public abstract class AbstractDojoContentPane extends UIOutput implements DojoWidget {

    public static final String COMPONENT_FAMILY = "javax.faces.Output";

    public static final String COMPONENT_TYPE   = "org.apache.myfaces.DojoContentPane";

    public static final String DEFAULT_RENDERER_TYPE    = "org.apache.myfaces.DojoContentPaneRenderer";

    /**
     * Path adjustment as defined by dojo
     * 
     * @JSFProperty
     */
    public abstract Boolean getAdjustPaths();

    /**
     * @JSFProperty
     */
    public abstract Boolean getCacheContent();

    /**
     * If true scripts will be evaled after rendering
     * 
     * @JSFProperty
     */
    public abstract Boolean getExecuteScripts();

    /**
     * Defined by dojo, see the examples
     * 
     * @JSFProperty
     */
    public abstract Boolean getExtractContent();

    public String getFamily() {
        return COMPONENT_FAMILY;
    }

    /**
     * Javascript function which should generate the content
     * 
     * @JSFProperty
     */
    public abstract String getHandler();

    /**
     * Remote href for iframe simulation
     * 
     * @JSFProperty
     */
    public abstract String getHref();

    /**
     * Layoutalignment usable in conjunction with a layout container
     * 
     * @JSFProperty
     */
    public abstract String getLayoutAlign();

    /**
     * Defined by dojo see the examples
     * 
     * @JSFProperty
     */
    public abstract Boolean getParseContent();

    /**
     * Content Preloading
     * 
     * @JSFProperty
     */
    public abstract Boolean getPreload();

    /**
     * Description for the attribute
     * 
     * @JSFProperty
     */
    public abstract Boolean getRefreshOnShow();

    /**
     * Size share value describing the place the content pane wants from its parent
     * 
     * @JSFProperty
     */
    public abstract Integer getSizeShare();

    /**
     * The CSS class for this element. Corresponds to the HTML 'class' attribute.
     * 
     * @JSFProperty
     */
    public abstract String getStyle();

    /**
     * The CSS class for this element. Corresponds to the HTML 'class' attribute.
     * 
     * @JSFProperty
     */
    public abstract String getStyleClass();

    /**
     * Optional enforced dojo widgetId
     * 
     * @JSFProperty
     */
    public abstract String getWidgetId();

    /**
     * optional widget var name, if this is not used only an autogenerated value 
     * is set
     * 
     * @JSFProperty
     */
    public abstract String getWidgetVar();

    /**
     * Scopecontainer for downloaded Scripts
     * 
     * @JSFProperty
     */
    public abstract String getScriptScope();
}
