/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.myfaces.custom.dojolayouts;

import org.apache.myfaces.custom.dojo.DojoWidget;

/**
 * PanelGroup which supports a partialTriggers Attribute similar to the one in Trinidad
 * 
 * @JSFComponent
 *   name = "s:floatingPane"
 *   class = "org.apache.myfaces.custom.dojolayouts.FloatingPaneBase"
 *   superClass = "org.apache.myfaces.custom.dojolayouts.AbstractFloatingPaneBase"
 *   parent = "javax.faces.component.UIOutput"
 *   tagClass = "org.apache.myfaces.custom.dojolayouts.FloatingPaneTag"
 *   
 *
 */
public abstract class AbstractFloatingPaneBase extends DojoContentPane implements DojoWidget {

    public static final String COMPONENT_FAMILY = "javax.faces.Output";

    public static final String COMPONENT_TYPE   = "org.apache.myfaces.FloatingPaneBase";

    public static final String DEFAULT_RENDERER_TYPE    = "org.apache.myfaces.FloatingPaneBaseRenderer";

    /**
     * limit to parent container
     * 
     * @JSFProperty
     */
    public abstract Boolean getConstrainToContainer();

    /**
     * if true a close button is displayed
     * 
     * @JSFProperty
     */
    public abstract Boolean getDisplayCloseAction();

    /**
     * if true a minimize button is displayed
     * 
     * @JSFProperty
     */
    public abstract Boolean getDisplayMinimizeAction();

    /**
     * Shadow drawn or not
     * 
     * @JSFProperty
     */
    public abstract Boolean getHasShadow();

    /**
     * The pane icon source
     * 
     * @JSFProperty
     */
    public abstract String getIconSrc();

    /**
     * Description for the attribute
     * 
     * @JSFProperty
     */
    public abstract Boolean getModal();

    /**
     * Window resizable
     * 
     * @JSFProperty
     */
    public abstract Boolean getResizable();

    /**
     * The taskbar id
     * 
     * @JSFProperty
     */
    public abstract String getTaskBarId();

    /**
     * the floating pane Title
     * 
     * @JSFProperty
     */
    public abstract String getTitle();

    /**
     * Displays the title bar of the Window
     * 
     * @JSFProperty
     */
    public abstract Boolean getTitleBarDisplay();

    /**
     * Optional enforced dojo widgetId
     * 
     * @JSFProperty
     */
    public abstract String getWidgetId();

    /**
     * optional widget var name, if this is not used only an autogenerated value is set
     * 
     * @JSFProperty
     */
    public abstract String getWidgetVar();

    /**
     * Display state of the window
     * 
     * @JSFProperty
     */
    public abstract String getWindowState();

}
